### ISSUE TITLE
Only 1 region in UK accounts

### ISSUE THREAD

**Issue by minac** [dman777/rackspace-cloud-files-tools#1]
Hi,

In script add_header_util_api_key.py , if the customer is from the UK, there is only one region displayed:

[{u'region': u'LON', u'publicURL': u'https://storage101.lon3.clouddrive.com/v1/MossoCloudFS_blahblah', u'internalURL': u'https://snet-storage101.lon3.clouddrive.com/v1/MossoCloudFS_blahblah', u'tenantId': u'MossoCloudFS_blahblah'}]

So the array explodes:
Traceback (most recent call last):
  File "add_header_util_api_key.py", line 164, in <module>
    cf, link = get_link(jsonrep)
  File "add_header_util_api_key.py", line 45, in get_link
    { str(bar["endpoints"][1]["region"]) : str(bar["endpoints"][1]["publicURL"]) },
IndexError: list index out of range

Can you please check the length of the array?

Thanks

**Comment by dman777** [comment]
Hi,

Sure! Thanks for letting me know! It might be a little while though. I am transferring to another team at work and I am ramping on other frameworks. I will be taking a vacation soon and I will try and hit it up. 

Thanks!

**Comment by minac** [comment]
This is stale, closing

**Comment by dman777** [comment]
Hi @minac , just curious....do you still use this tool? I keep it up because there is no cost but I was wondering if anyone still uses it.

**Comment by minac** [comment]
I don't, for a long time now.
